### ISSUE TITLE
Incorrect status on failing delete cluster rest api call

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#1109]
![image](https://user-images.githubusercontent.com/15246294/30963504-ef4df808-a44d-11e7-9661-c9ed96a90258.png)

**Comment by serboctor** [comment]
Geert can't remember the error in ays so I don't know how to reproduce the exact same scenario. Also,  the templates and apis of the storagecluster changed a lot since this issue was created.  
For the sake of testing, I manually raised an exception during the execution of blueprints in ays, but the returned status is correct. 
![deletecluster](https://user-images.githubusercontent.com/6323012/31503208-5a16fb5e-af6f-11e7-8c3b-da4a26199b5a.png)

**Comment by ahmedelsayed-93** [comment]
### software version 
master : 5c7668358
