### ISSUE TITLE
Container created with fake directory in init process

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-orchestrator#226]
## Request
![selection_335](https://cloud.githubusercontent.com/assets/24386802/26035646/f04b9ea2-38cf-11e7-8225-ed824e8bfdda.png)
## Response
![selection_336](https://cloud.githubusercontent.com/assets/24386802/26035666/355d19a8-38d0-11e7-8067-3ab771f64c24.png)
 
container created !
## SV 
resourcepool : a30a8b47653db98bbb80d4039a7e5722ccfa156c

**Comment by abdulrahmantkhalifa** [comment]
to be discussed on 2017-05-16

**Comment by muhamadazmy** [comment]
I personally think it will be over kill to handle this client side. It will be more efficient to handle this on core0 itself (Still gonna be tricky to do). 
I suggest that a container create can take an extra `init` param with a command line to what to start on container creation, and stop the container with an error if the init didn't start as expected.
Due to the asynchronous nature of core0 and coreX container creation might be marked as successful before corex get the chance to report the error, hence the tricky part.
