### ISSUE TITLE
VM with vdisk block size less than 4096, doesn't boot

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-orchestrator#965]
## Steps
- create  vm with this vdisk
{
  "id": "vdisk6",
  "size": 15,
  "blocksize": 1024,
  "type": "boot",
  "templatevdisk": "ardb:///template:ubuntu-1604",
  "blockStoragecluster": "st"
}
- check vm status , will be running 
- try to login to vm , vm will not boot 
## Issue 
If size doesn't enough for  template,should be prevented from beginnig

**Comment by GlenDC** [comment]
The problem here is not the block size. 1024 is `a power of 2` and `greater than 512`, so that isn't what is stopping you.

The error here is the property `templatevdisk` is wrong. The property is named `templateVdiskID`. See https://github.com/zero-os/0-Disk/blob/master/docs/config.md#VdiskStaticConfig for more information (docs are pretty useful).

I suppose you don't get an error from this at startup as `templatevdisk` won't be recognized and thus just ignored. Sadly because the fact that 0-Orchestrator also adds unknown properties on purpose to the ETCD 0-Disk configs, we cannot unmarshal in strict mode. If we could this would also be an error we can detect at startup time.

However while there is no error on runtime, if you would run the `nbdserver` using the verbose (`-v`) flag, you should see logged debug lines containing content such as: `content not available in primary storage for vdisk6 and no template storage available: ...`, which should make you think that the problem is really with the template storage.

Either way, as we cannot do strict unmarshalling, it is even more important you read and know the config docs very well.

**Comment by khaledkbadr** [comment]
I believe this issue is due to we populated the ubuntu template in hub.gig.tech using 4096 blocksize, and you specified 1024  when creating it. I will block this issue on https://github.com/zero-os/0-orchestrator/issues/1005 since it proposes a fix for that conflict

**Comment by FastGeert** [comment]
This issue is outdated since an export of a vdisk now also writes this kind of metadata in the export to the ftp server. Also the zero-ctl command does accept the blocksize parameter anymore.
